name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Change working directory
        run: cd ${{ github.workspace }}

      - name: Set up Python Path
        run: |
          import sys
          sys.path.append('.')
          print(sys.path)
        shell: python

      - name: Install project (editable)
        run: pip install -e . || true # Keep this, but allow failure

      - name: Run tests with pytest
        run: pytest tests/test_main.py
        working-directory: ${{ github.workspace }}